version: '3.4'

services:
  modeler:
    build: ./modeler
    network_mode: host
    environment: {DISPLAY:}
    working_dir: /models
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority
      - ./classes:/models

  platform:
    image: camunda/camunda-bpm-platform:latest
    ports: [80:8080]
    volumes:
      - ./classes/:/camunda/webapps/camunda-invoice/WEB-INF/classes/
